# Generated by Django 5.2.7 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
