# Generated by Django 5.2.4 on 2026-02-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_attendance_session'),
        ('students', '0006_cvrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-date', 'period']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancereport',
            unique_together={('student', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('date', 'period', 'class_name', 'section')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.subject'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='attendance.subject'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.subject'),
        ),
    ]
