# Generated by Django 5.2.4 on 2026-02-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancesession_options_and_more'),
    ]

    def copy_subject_names_forward(apps, schema_editor):
        Attendance = apps.get_model('attendance', 'Attendance')
        AttendanceSession = apps.get_model('attendance', 'AttendanceSession')
        AttendanceReport = apps.get_model('attendance', 'AttendanceReport')
        Subject = apps.get_model('attendance', 'Subject')

        # Copy for Attendance
        for att in Attendance.objects.all():
            if att.subject:
                att.subject_name = att.subject.name
                att.save(update_fields=['subject_name'])

        # Copy for AttendanceSession
        for sess in AttendanceSession.objects.all():
            if sess.subject:
                sess.subject_name = sess.subject.name
                sess.save(update_fields=['subject_name'])

        # Copy for AttendanceReport
        for rep in AttendanceReport.objects.all():
            if rep.subject:
                rep.subject_name = rep.subject.name
                rep.save(update_fields=['subject_name'])

    def noop_reverse(apps, schema_editor):
        # No-op: we won't remove copied names on reverse automatically
        return

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='subject_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='subject_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(copy_subject_names_forward, noop_reverse),
    ]
